
int bitAnd(int, int);
int test_bitAnd(int, int);
int bitXor(int, int);
int test_bitXor(int, int);
int isEqual(int, int);
int test_isEqual(int, int);
int evenBits();
int test_evenBits();
int fitsBits(int, int);
int test_fitsBits(int, int);
int bitMask(int, int);
int test_bitMask(int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int reverseBytes(int);
int test_reverseBytes(int);
int bang(int);
int test_bang(int);
int bitCount(int);
int test_bitCount(int);
int isZero(int);
int test_isZero(int);
int isNegative(int);
int test_isNegative(int);
int multFiveEights(int);
int test_multFiveEights(int);
int sum3(int, int, int);
int test_sum3(int, int, int);
int addOK(int, int);
int test_addOK(int, int);
int isLess(int, int);
int test_isLess(int, int);
int abs(int);
int test_abs(int);
int isNonZero(int);
int test_isNonZero(int);
int tc2sm(int);
int test_tc2sm(int);
